In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size = 10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### one hot representation
onehot_repr = [one_hot(words, voc_size) for words in sent]
onehot_repr

[[3320, 3417, 6777, 7807],
 [3320, 3417, 6777, 6522],
 [3320, 7313, 6777, 3682],
 [659, 4879, 1816, 9426, 2978],
 [659, 4879, 1816, 9426, 4327],
 [610, 3320, 9686, 6777, 4957],
 [2975, 9705, 1071, 9426]]

In [7]:
## Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [8]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3320 3417 6777 7807]
 [   0    0    0    0 3320 3417 6777 6522]
 [   0    0    0    0 3320 7313 6777 3682]
 [   0    0    0  659 4879 1816 9426 2978]
 [   0    0    0  659 4879 1816 9426 4327]
 [   0    0    0  610 3320 9686 6777 4957]
 [   0    0    0    0 2975 9705 1071 9426]]


In [9]:
## feature representation using embedding
embedding_dim = 10

In [10]:
model = Sequential()
model.add(Embedding(voc_size, embedding_dim, input_length=sent_length))
model.compile('adam', 'mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 137ms/step


array([[[-4.74721678e-02,  4.78003882e-02,  9.70701128e-03,
         -1.16361156e-02,  4.64082845e-02, -3.09651624e-02,
         -4.21858951e-03,  1.12443678e-02, -8.26292112e-03,
          4.18170542e-03],
        [-4.74721678e-02,  4.78003882e-02,  9.70701128e-03,
         -1.16361156e-02,  4.64082845e-02, -3.09651624e-02,
         -4.21858951e-03,  1.12443678e-02, -8.26292112e-03,
          4.18170542e-03],
        [-4.74721678e-02,  4.78003882e-02,  9.70701128e-03,
         -1.16361156e-02,  4.64082845e-02, -3.09651624e-02,
         -4.21858951e-03,  1.12443678e-02, -8.26292112e-03,
          4.18170542e-03],
        [-4.74721678e-02,  4.78003882e-02,  9.70701128e-03,
         -1.16361156e-02,  4.64082845e-02, -3.09651624e-02,
         -4.21858951e-03,  1.12443678e-02, -8.26292112e-03,
          4.18170542e-03],
        [ 1.77331604e-02, -3.66521999e-03, -2.07949039e-02,
          2.94930600e-02, -2.51917001e-02,  4.67519499e-02,
          4.25091125e-02,  3.37487124e-02,  2.872646

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 3320, 3417, 6777, 7807])

In [14]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 40ms/step


array([[-4.74721678e-02,  4.78003882e-02,  9.70701128e-03,
        -1.16361156e-02,  4.64082845e-02, -3.09651624e-02,
        -4.21858951e-03,  1.12443678e-02, -8.26292112e-03,
         4.18170542e-03],
       [-4.74721678e-02,  4.78003882e-02,  9.70701128e-03,
        -1.16361156e-02,  4.64082845e-02, -3.09651624e-02,
        -4.21858951e-03,  1.12443678e-02, -8.26292112e-03,
         4.18170542e-03],
       [-4.74721678e-02,  4.78003882e-02,  9.70701128e-03,
        -1.16361156e-02,  4.64082845e-02, -3.09651624e-02,
        -4.21858951e-03,  1.12443678e-02, -8.26292112e-03,
         4.18170542e-03],
       [-4.74721678e-02,  4.78003882e-02,  9.70701128e-03,
        -1.16361156e-02,  4.64082845e-02, -3.09651624e-02,
        -4.21858951e-03,  1.12443678e-02, -8.26292112e-03,
         4.18170542e-03],
       [ 1.77331604e-02, -3.66521999e-03, -2.07949039e-02,
         2.94930600e-02, -2.51917001e-02,  4.67519499e-02,
         4.25091125e-02,  3.37487124e-02,  2.87264697e-02,
        -4.